require: rubocop-rails
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 3.4.1
  TargetRailsVersion: 7.2
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml
