#!/usr/bin/env sh
bundle lock --add-platform aarch64-linux
npx lint-staged
printf "Changed Files:"
# staged filenames, filter out deleted
changed_files=$(git diff --name-only --staged HEAD --diff-filter=d | grep -E '\.(erb)$') && echo "$changed_files"
if [ -n "$changed_files" ]; then
  printf "Running erblint..."
  bundle exec erblint $changed_files --autocorrect
  git fetch
  git add $changed_files
fi
